import type { Project } from './types'

export const projects: Project[] = [
  {
    id: 1,
    category: 'Portfolio & Showcase',
    title: 'ahmetakyapi.com',
    description: 'Bu sitenin kendisi. Next.js App Router, TailwindCSS ve Framer Motion ile sıfırdan tasarlayıp geliştirdiğim kişisel portfolio ve blog sitesi. Dark/light tema, Giscus yorum sistemi ve teknik blog yazıları içeriyor.',
    tags: ['Next.js', 'TypeScript', 'TailwindCSS', 'Framer Motion'],
    link: 'https://ahmetakyapi.com',
    github: 'https://github.com/ahmetakyapi/ahmetakyapi.me',
    accent: '#6366f1',
    gradient: 'linear-gradient(135deg, #6366f1 0%, #8b5cf6 50%, #a855f7 100%)',
    badge: 'Canlı',
    featured: true,
  },
  {
    id: 2,
    category: 'Productivity',
    title: 'DigyNotes',
    description: 'Minimalist dijital not alma uygulaması. Notları başlık ve içerikle hızlıca oluşturup kategorilere göre düzenleyebilir, anlık arama yapabilirsin. TypeScript ile tip güvenli geliştirildi.',
    tags: ['TypeScript', 'React', 'TailwindCSS'],
    link: 'https://digy-notes.vercel.app',
    github: 'https://github.com/ahmetakyapi/DigyNotes',
    accent: '#8b5cf6',
    gradient: 'linear-gradient(135deg, #8b5cf6 0%, #6366f1 100%)',
    badge: 'Canlı',
    featured: false,
  },
  {
    id: 3,
    category: 'Finance',
    title: 'Keşke Alsaydım',
    description: '"Keşke o zaman o hisseyi alsaydım" hissini sayıya döken araç. Geçmişe dönüp seçtiğin varlığa yatırım yapsaydın bugün ne kadar olurdu sorusunu yanıtlıyor.',
    tags: ['TypeScript', 'React', 'TailwindCSS'],
    link: 'https://keskealsaydim.vercel.app',
    github: 'https://github.com/ahmetakyapi/keskealsaydim',
    accent: '#10b981',
    gradient: 'linear-gradient(135deg, #10b981 0%, #059669 100%)',
    badge: 'Canlı',
    featured: false,
  },
  {
    id: 4,
    category: 'Utility',
    title: 'Ramazan Vakitleri',
    description: "Türkiye'nin 81 ili için güncel iftar ve sahur vakitlerini listeleyen sade web uygulaması. İl seçimine göre otomatik filtreleme.",
    tags: ['JavaScript', 'HTML', 'CSS'],
    link: 'https://ramazan-vakitleri.vercel.app',
    github: 'https://github.com/ahmetakyapi/ramazan-vakitleri',
    accent: '#f59e0b',
    gradient: 'linear-gradient(135deg, #f59e0b 0%, #d97706 100%)',
    badge: 'Canlı',
    featured: false,
  },
  {
    id: 5,
    category: 'Clinical SaaS',
    title: 'Mimio',
    description: 'Ergoterapistlerin klinik sürecini dijitalleştiren bir platform. Danışan profili, haftalık program, altı farklı terapi oyunu ve ilerleme grafiği tek panelde toplanıyor. AOTA çerçevesine uygun hazırlandı, Neon Postgres üstünde koşuyor.',
    tags: ['Next.js 15', 'TypeScript', 'Tailwind v4', 'Neon', 'Framer Motion'],
    link: 'https://mimios.vercel.app',
    github: 'https://github.com/ahmetakyapi/Mimio',
    accent: '#6366f1',
    gradient: 'linear-gradient(135deg, #6366f1 0%, #7c3aed 50%, #a855f7 100%)',
    badge: 'Canlı',
    featured: true,
  },
  {
    id: 6,
    category: 'Fan Platform',
    title: 'One Piece Hub',
    description: 'OnePaceTR bölüm numaralarını ark tabanlı bir izleme sistemine çeviren Türkçe fan platformu. 463 bölüm 36 arka bölünüyor, 66 karakter için ilişki grafı, arka göre quiz modu ve Cmd+K arama var. Koyu temalı sinematik bir wiki hissi hedefledim.',
    tags: ['Next.js 14', 'TypeScript', 'Drizzle', 'Neon', 'JWT'],
    link: 'https://onepiece-hub.vercel.app',
    github: 'https://github.com/ahmetakyapi/onepiece-hub',
    accent: '#ef4444',
    gradient: 'linear-gradient(135deg, #ef4444 0%, #f59e0b 100%)',
    badge: 'Canlı',
    featured: true,
  },
  {
    id: 7,
    category: 'Multiplayer Game',
    title: 'Karalama',
    description: 'Kayıt gerektirmeyen, Türkçe kelime havuzuyla oynanan bir çok oyunculu çizim oyunu. 18 kategoride 1070+ kelime, Socket.io ile gerçek zamanlı çizim ve tahmin akışı, mobil uyumlu sahne. Bir bağlantı paylaş, oynamaya başla.',
    tags: ['Next.js 14', 'Socket.io', 'Zustand', 'TypeScript', 'Monorepo'],
    link: 'https://karalama.vercel.app',
    github: 'https://github.com/ahmetakyapi/karalama',
    accent: '#22d3ee',
    gradient: 'linear-gradient(135deg, #22d3ee 0%, #0ea5e9 100%)',
    badge: 'Canlı',
    featured: false,
  },
  {
    id: 8,
    category: 'Multiplayer Game',
    title: 'Dungeon Mates',
    description: '2-4 kişilik kooperatif zindan macerası. Tarayıcı üstünde koşuyor, yükleme yok. BSP algoritmasıyla üretilen prosedürel haritalar, üç karakter sınıfı, dokuz düşman tipi ve 2600 satırlık prosedürel sprite kodu. Sunucu otoriter, hile korumalı.',
    tags: ['Next.js 14', 'Canvas', 'Socket.io', 'WebAudio', 'TypeScript'],
    link: 'https://dungeon-mates.vercel.app',
    github: 'https://github.com/ahmetakyapi/dungeon-mates',
    accent: '#10b981',
    gradient: 'linear-gradient(135deg, #10b981 0%, #0d9488 100%)',
    badge: 'Canlı',
    featured: false,
  },
]
