import type { Project } from './types'

export const projects: Project[] = [
  {
    id: 1,
    category: 'Finansal Takip',
    title: 'Açılış Zili',
    shot: 'acilis-zili',
    description:
      'ABD piyasasını kendi takibim için tek ekrana indiren site. Bilanço takvimi ve her bilanço için yazılan analizler, 500\'ü aşkın şirketlik dizin, makro göstergeler, haberler ve takip listesi bir arada. Üstüne her gün yazılan bülten ve olay bazlı uzun yazılar.',
    detail:
      'Analizlerde oran değil oranın böleni saklanıyor: F/K\'nin payı fiyat olduğu için kaydedilen oran ertesi gün yanlış olmaya başlıyor. Her kartın altında kaynak ve saat damgası var; veri yoksa kart boş kalıyor.',
    tags: ['Next.js 16', 'React 19', 'Tailwind v4', 'Drizzle', 'Neon', 'next-auth v5'],
    link: 'https://acilis-zili.vercel.app',
    github: 'https://github.com/ahmetakyapi/acilis-zili',
    accent: '#0d74c4',
    gradient: 'linear-gradient(135deg, #0d74c4 0%, #0a5a9a 50%, #101c2b 100%)',
    badge: 'Canlı',
    featured: true,
    preview: 'ticker',
    postSlug: 'acilis-zili-nasil-yapildi',
    stats: [
      { value: '15', label: 'tablo' },
      { value: '24', label: 'sayfa' },
      { value: '4', label: 'veri sağlayıcı' },
    ],
  },
  {
    id: 2,
    category: 'Klinik SaaS',
    title: 'Mimio',
    shot: 'mimio',
    description:
      'Ergoterapistlerin danışan takibini, seans planlamasını ve terapi sürecini tek panelde yönetmesi için kurulan klinik platform. Danışan profilleri, haftalık akış, terapi oyunları ve ilerleme grafikleri aynı sistemin içinde.',
    detail:
      'Seans notları SOAP standardında tutuluyor — kendi alanlarımı uydurmak yerine mesleğin zaten kullandığı formatı aldım. Yedi terapi oyununun skorları danışan dosyasına düşüyor.',
    tags: ['Next.js 15', 'TypeScript', 'Tailwind v4', 'Neon', 'Framer Motion'],
    link: 'https://mimios.vercel.app',
    github: 'https://github.com/ahmetakyapi/Mimio',
    accent: '#2b62f5',
    gradient: 'linear-gradient(135deg, #2b62f5 0%, #1d8ad4 55%, #17c2e0 100%)',
    badge: 'Canlı',
    featured: true,
    preview: 'board',
    postSlug: 'bilmedigim-meslege-arac-yazmak',
  },
  {
    id: 3,
    category: 'Fan Platformu',
    title: 'One Piece Hub',
    shot: 'onepiece-hub',
    description:
      'One Piece evrenini Türkçe içerikle düzenli ve keşfedilebilir hale getiren fan platformu. Ark takibi, karakter ilişkileri, quiz modu ve hızlı arama tek bir sinematik wiki deneyiminde birleşiyor.',
    detail:
      'Spoiler kapısı var: hangi arkta olduğunu söylüyorsun, sonrasına ait her şey bulanıklaşıyor. Ekran okuyucuya da içerik sızmıyor.',
    tags: ['Next.js 14', 'TypeScript', 'Drizzle', 'Neon', 'JWT'],
    link: 'https://onepiece-hub.vercel.app',
    github: 'https://github.com/ahmetakyapi/onepiece-hub',
    accent: '#ef4444',
    gradient: 'linear-gradient(135deg, #ef4444 0%, #f59e0b 100%)',
    badge: 'Canlı',
    featured: true,
    preview: 'grid',
    postSlug: 'spoiler-vermeyen-wiki',
  },
  {
    id: 4,
    category: 'Günlük Oyun',
    title: 'Harfiyen',
    shot: 'harfiyen',
    description:
      'Her gün saat 09:00\'da üç yeni Türkçe kare bulmaca: 6×6 kolay, 8×8 orta, 10×10 zor. Süre bazlı liderlik tablosu, seri takibi ve geçmiş günlere dönebildiğin bir arşiv var.',
    detail:
      'Cevaplar istemciye hiç gitmiyor, süre sunucu saatiyle ölçülüyor. Bulmaca havuzu kelime bankasından toplu üretiliyor.',
    tags: ['Next.js', 'TypeScript', 'Drizzle', 'Neon', 'Vitest'],
    link: 'https://harfiyen.vercel.app',
    github: 'https://github.com/ahmetakyapi/harfiyen',
    accent: '#f59e0b',
    gradient: 'linear-gradient(135deg, #f59e0b 0%, #ea580c 100%)',
    badge: 'Canlı',
    featured: false,
    preview: 'grid',
  },
  {
    id: 5,
    category: 'Çok Oyunculu Oyun',
    title: 'ElevenForge',
    shot: 'elevenforge',
    description:
      '16 arkadaşın aynı ligde yarıştığı Türkçe futbol menajerlik oyunu. Davet koduyla katılıyorsun, boş kalan yerleri bot dolduruyor ve maçlar ligi kuran kişinin seçtiği saatte simüle ediliyor.',
    detail:
      'Maç motoru deterministik: fikstür kimliğinden üretilen tohum, aynı maçı tekrar oynattığında aynı skoru veriyor. Transfer pazarında iyimser kilitleme var — on alıcıdan yalnızca biri kazanıyor.',
    tags: ['Next.js 16', 'React 19', 'Drizzle', 'TypeScript', 'Cron'],
    link: 'https://elevenforge.vercel.app',
    github: 'https://github.com/ahmetakyapi/elevenforge',
    accent: '#22c55e',
    gradient: 'linear-gradient(135deg, #22c55e 0%, #15803d 100%)',
    badge: 'Canlı',
    featured: false,
    preview: 'board',
  },
  {
    id: 6,
    category: 'Üretkenlik',
    title: 'DigyNotes',
    shot: 'digynotes',
    description:
      'Sade ama işlevli bir dijital not uygulaması. Notları hızlıca oluşturup kategorilere ayırıyor, içerik içinde anlık arama yapıyor ve günlük kullanımda dikkat dağıtmayan bir akış sunuyor.',
    tags: ['TypeScript', 'React', 'TailwindCSS'],
    link: 'https://digy-notes.vercel.app',
    github: 'https://github.com/ahmetakyapi/DigyNotes',
    accent: '#10b981',
    gradient: 'linear-gradient(135deg, #10b981 0%, #059669 100%)',
    badge: 'Canlı',
    featured: false,
    preview: 'notes',
  },
  {
    id: 7,
    category: 'Çok Oyunculu Oyun',
    title: 'Karalama',
    shot: 'karalama',
    description:
      'Kayıt olmadan arkadaşlarla hızlıca oynanan çok oyunculu çizim oyunu. Türkçe kelime havuzu, oda tabanlı gerçek zamanlı akış ve mobil uyumlu bir sahne — bağlantıyı paylaşır paylaşmaz oyun başlıyor.',
    detail: 'Socket.io üzerinde oda tabanlı durum yönetimi; sunucu otoriteli tur akışı.',
    tags: ['Next.js 14', 'Socket.io', 'Zustand', 'TypeScript', 'Monorepo'],
    link: 'https://karalama.vercel.app',
    github: 'https://github.com/ahmetakyapi/karalama',
    accent: '#22d3ee',
    gradient: 'linear-gradient(135deg, #22d3ee 0%, #0ea5e9 100%)',
    badge: 'Canlı',
    featured: false,
    preview: 'board',
    postSlug: 'socket-io-ile-oda-tabanli-multiplayer',
  },
  {
    id: 8,
    category: 'Çok Oyunculu Oyun',
    title: 'Dungeon Mates',
    shot: 'dungeon-mates',
    description:
      'Tarayıcıda çalışan, 2-4 kişilik kooperatif zindan oyunu. Prosedürel haritalar, farklı sınıflar ve sunucu otoriteli yapı sayesinde her tur yeniden oynanmak isteniyor.',
    detail: 'Haritalar BSP ile üretiliyor ve sunucuda tek yerden dağıtılıyor — istemciler kendi zindanını üretmiyor.',
    tags: ['Next.js 14', 'Canvas', 'Socket.io', 'WebAudio', 'TypeScript'],
    link: 'https://dungeon-mates.vercel.app',
    github: 'https://github.com/ahmetakyapi/dungeon-mates',
    accent: '#a855f7',
    gradient: 'linear-gradient(135deg, #a855f7 0%, #6366f1 100%)',
    badge: 'Canlı',
    featured: false,
    preview: 'grid',
    postSlug: 'bsp-ile-prosedurel-zindan-uretmek',
  },
  {
    id: 9,
    category: 'Klinik Panel',
    title: 'Derinay',
    shot: 'derinay',
    description:
      'Tek kişilik bir klinik pratiğin yönetim paneli: gelir-gider, danışan, seans, fatura, ödeme ve vergi takibi tek sakin arayüzde toplanıyor.',
    detail:
      'Grafikler ana pakete girmiyor — Recharts ayrı bir lazy katmandan yükleniyor. Varsayılan tema açık.',
    tags: ['Next.js 14', 'Drizzle', 'Neon', 'Recharts', 'next-auth v5'],
    link: 'https://derinay.vercel.app',
    github: 'https://github.com/ahmetakyapi/derinay',
    accent: '#0ea5e9',
    gradient: 'linear-gradient(135deg, #0ea5e9 0%, #0369a1 100%)',
    badge: 'Canlı',
    featured: false,
    preview: 'chart',
  },
  {
    id: 10,
    category: 'Finans',
    title: 'Keşke Alsaydım',
    shot: 'keskealsaydim',
    description:
      '"O gün alsaydım bugün ne olurdu?" sorusunu sayıya döken küçük ama merak uyandıran bir araç. Seçtiğin varlığa geçmişte yatırım yapsaydın bugünkü karşılığını hızlı ve anlaşılır biçimde gösteriyor.',
    tags: ['TypeScript', 'React', 'TailwindCSS'],
    link: 'https://keskealsaydim.vercel.app',
    github: 'https://github.com/ahmetakyapi/keskealsaydim',
    accent: '#14b8a6',
    gradient: 'linear-gradient(135deg, #14b8a6 0%, #0d9488 100%)',
    badge: 'Canlı',
    featured: false,
    preview: 'chart',
  },
  {
    id: 11,
    category: 'Geliştirici Aracı',
    title: 'dev-starter',
    description:
      'Kendi geliştirme ekosistemim: tasarım tokenları, paylaşılan UI bileşenleri, Next.js şablonları ve projeler arası ortak kural seti. İki npm paketi olarak yayımlanıyor.',
    detail: '@ahmetakyapi/theme ve @ahmetakyapi/ui — token katmanı ve bileşen katmanı ayrı paketlerde.',
    tags: ['TypeScript', 'npm', 'Monorepo', 'Tailwind'],
    link: 'https://github.com/ahmetakyapi/dev-starter',
    github: 'https://github.com/ahmetakyapi/dev-starter',
    accent: '#6366f1',
    gradient: 'linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%)',
    badge: 'GitHub',
    featured: false,
    preview: 'notes',
  },
  {
    id: 12,
    category: 'Yardımcı Araç',
    title: 'Ramazan Vakitleri',
    shot: 'ramazan-vakitleri',
    description:
      "Türkiye'nin 81 ili için iftar ve sahur vakitlerini gösteren hafif bir web uygulaması. İl seçimine göre anında filtreleniyor; özellikle mobilde sade ve doğrudan bir deneyim sunuyor.",
    tags: ['JavaScript', 'HTML', 'CSS'],
    link: 'https://ramazan-vakitleri.vercel.app',
    github: 'https://github.com/ahmetakyapi/ramazan-vakitleri',
    accent: '#f59e0b',
    gradient: 'linear-gradient(135deg, #f59e0b 0%, #d97706 100%)',
    badge: 'Canlı',
    featured: false,
    preview: 'notes',
  },
  {
    id: 13,
    category: 'Portfolyo',
    title: 'ahmetakyapi.com',
    description:
      'Bu site. Portfolyo ve teknik blog tek çatı altında. Animasyon kütüphanesi yok — geçişler, kart eğimi ve görünüme girme animasyonlarının tamamı CSS ile yazıldı; ilk yükleme JavaScript\'i 104 KB.',
    tags: ['Next.js', 'TypeScript', 'TailwindCSS', 'Satori OG'],
    link: 'https://ahmetakyapi.com',
    github: 'https://github.com/ahmetakyapi/ahmetakyapi.com',
    accent: '#8b5cf6',
    gradient: 'linear-gradient(135deg, #6366f1 0%, #8b5cf6 50%, #a855f7 100%)',
    badge: 'Canlı',
    featured: false,
    preview: 'browser',
    postSlug: 'olculen-hiz-hissedilen-hiz',
  },
]
