import type { Project } from './types'

export const projects: Project[] = [
  {
    id: 1,
    category: 'Finansal Takip',
    title: 'Açılış Zili',
    slug: 'acilis-zili',
    group: 'platform',
    description:
      'ABD piyasasını kendi takibim için tek ekrana indiren site. Bilanço takvimi ve her bilanço için yazılan analizler, 500\'ü aşkın şirketlik dizin, makro göstergeler, haberler ve takip listesi bir arada. Üstüne her gün yazılan bülten ve olay bazlı uzun yazılar.',
    detail:
      'Analizlerde oran değil oranın böleni saklanıyor: F/K\'nin payı fiyat olduğu için kaydedilen oran ertesi gün yanlış olmaya başlıyor. Her kartın altında kaynak ve saat damgası var; veri yoksa kart boş kalıyor.',
    tags: ['Next.js 16', 'React 19', 'Tailwind v4', 'Drizzle', 'Neon', 'next-auth v5'],
    link: 'https://aciliszili.com',
    github: 'https://github.com/ahmetakyapi/acilis-zili',
    accent: '#0d74c4',
    tint: '#0d74c4',
    gradient: 'linear-gradient(135deg, #0d74c4 0%, #0a5a9a 50%, #101c2b 100%)',
    badge: 'Canlı',
    featured: true,
    postSlug: 'acilis-zili-nasil-yapildi',
    stats: [
      { value: '31', label: 'Postgres Tablosu' },
      { value: '53', label: 'Sayfa' },
      { value: '9', label: 'Veri Kaynağı' },
    ],
  },
  {
    id: 2,
    category: 'Klinik SaaS',
    title: 'Mimio',
    slug: 'mimio',
    group: 'platform',
    description:
      'Ergoterapistlerin danışan takibini, seans planlamasını ve terapi sürecini tek panelde yönetmesi için kurulan klinik platform. Danışan profilleri, haftalık akış, terapi oyunları ve ilerleme grafikleri aynı sistemin içinde.',
    detail:
      'Seans notları SOAP standardında tutuluyor; kendi alanlarımı uydurmak yerine mesleğin zaten kullandığı formatı aldım. Yedi terapi oyununun skorları danışan dosyasına düşüyor.',
    tags: ['Next.js 15', 'TypeScript', 'Tailwind v4', 'Neon', 'Framer Motion'],
    link: 'https://mimios.vercel.app',
    github: 'https://github.com/ahmetakyapi/Mimio',
    accent: '#2b62f5',
    tint: '#2b62f5',
    gradient: 'linear-gradient(135deg, #2b62f5 0%, #1d8ad4 55%, #17c2e0 100%)',
    badge: 'Canlı',
    featured: false,
    postSlug: 'bilmedigim-meslege-arac-yazmak',
  },
  {
    id: 3,
    category: 'Fan Platformu',
    title: 'One Piece Hub',
    slug: 'onepiece-hub',
    group: 'platform',
    description:
      'One Piece evrenini Türkçe içerikle düzenli ve keşfedilebilir hale getiren fan platformu. Ark takibi, karakter ilişkileri, quiz modu ve hızlı arama aynı sitede.',
    detail:
      'Spoiler kapısı var: hangi arkta olduğunu söylüyorsun, sonrasına ait her şey bulanıklaşıyor. Ekran okuyucuya da içerik sızmıyor.',
    tags: ['Next.js 14', 'TypeScript', 'Drizzle', 'Neon', 'JWT'],
    link: 'https://onepiece-hub.vercel.app',
    github: 'https://github.com/ahmetakyapi/onepiece-hub',
    accent: '#ef4444',
    tint: '#c8902e',
    gradient: 'linear-gradient(135deg, #ef4444 0%, #f59e0b 100%)',
    badge: 'Canlı',
    featured: true,
    postSlug: 'spoiler-vermeyen-wiki',
  },
  {
    id: 4,
    category: 'Günlük Oyun',
    title: 'Harfiyen',
    slug: 'harfiyen',
    group: 'oyun',
    description:
      'Her gün saat 09:00\'da üç yeni Türkçe kare bulmaca: 6×6 kolay, 8×8 orta, 10×10 zor. Süre bazlı liderlik tablosu, seri takibi ve geçmiş günlere dönebildiğin bir arşiv var.',
    detail:
      'Cevaplar istemciye hiç gitmiyor, süre sunucu saatiyle ölçülüyor. Bulmaca havuzu kelime bankasından toplu üretiliyor.',
    tags: ['Next.js', 'TypeScript', 'Drizzle', 'Neon', 'Vitest'],
    link: 'https://harfiyen.vercel.app',
    github: 'https://github.com/ahmetakyapi/harfiyen',
    accent: '#f59e0b',
    gradient: 'linear-gradient(135deg, #f59e0b 0%, #ea580c 100%)',
    badge: 'Canlı',
    featured: false,
  },
  {
    id: 5,
    category: 'Çok Oyunculu Oyun',
    title: 'ElevenForge',
    slug: 'elevenforge',
    group: 'oyun',
    description:
      '16 arkadaşın aynı ligde yarıştığı Türkçe futbol menajerlik oyunu. Davet koduyla katılıyorsun, boş kalan yerleri bot dolduruyor ve maçlar ligi kuran kişinin seçtiği saatte simüle ediliyor.',
    detail:
      'Maç motoru deterministik: fikstür kimliğinden üretilen tohum, aynı maçı tekrar oynattığında aynı skoru veriyor. Transfer pazarında iyimser kilitleme var: on alıcıdan yalnızca biri kazanıyor.',
    tags: ['Next.js 16', 'React 19', 'Drizzle', 'TypeScript', 'Cron'],
    link: 'https://elevenforge.vercel.app',
    github: 'https://github.com/ahmetakyapi/elevenforge',
    accent: '#22c55e',
    gradient: 'linear-gradient(135deg, #22c55e 0%, #15803d 100%)',
    badge: 'Canlı',
    featured: false,
  },
  {
    id: 6,
    category: 'Üretkenlik',
    title: 'DigyNotes',
    slug: 'digynotes',
    group: 'arac',
    description:
      'İzlediğin film ve dizileri, oynadığın oyunları, okuduğun kitapları ve gezdiğin yerleri not ettiğin kişisel bir arşiv. Her kayda yarım puanlık adımlarla 5 üzerinden puan, izlendi ya da izlenecek gibi bir durum, etiketler ve zengin metinli bir inceleme ekleniyor. Başka kullanıcıları takip edip akışlarını görebiliyor, notlarını koleksiyonlara ayırıp bir istek listesi tutabiliyorsun.',
    detail:
      'Kayıt açarken adını yazman yetiyor; kapak, yönetmen, yazar ya da geliştirici ve yıl her türün kendi kaynağından doluyor. Film ve dizi TMDB\'den (önce Türkçe aranıyor, sonuç yoksa İngilizce), oyun RAWG\'den, kitap Open Library\'den, gezi yerleri OpenStreetMap\'ten geliyor.',
    tags: ['Next.js 14', 'TypeScript', 'Prisma', 'Neon', 'NextAuth', 'Tailwind CSS'],
    link: 'https://digy-notes.vercel.app',
    github: 'https://github.com/ahmetakyapi/DigyNotes',
    accent: '#10b981',
    gradient: 'linear-gradient(135deg, #10b981 0%, #059669 100%)',
    badge: 'Canlı',
    featured: false,
  },
  {
    id: 7,
    category: 'Çok Oyunculu Oyun',
    title: 'Karalama',
    slug: 'karalama',
    group: 'oyun',
    onlyDark: true,
    description:
      'Kayıt olmadan, bir bağlantıyla arkadaşlarınla oynadığın Türkçe çizim ve tahmin oyunu. Sırası gelen kelimesini seçip çiziyor, ötekiler sohbete tahmin yazıyor; süre azaldıkça kelimenin iki harfi ipucu olarak açılıyor ve erken bilen daha çok puan alıyor. Havuzda 18 kategoride 1.071 kelime var, oda kurucusu kendi kelimelerini ekleyebiliyor, kişi azsa lobiye bot çağırabiliyor.',
    detail:
      'Oyunun durumu Railway\'de çalışan ayrı bir Socket.io sunucusunda, arayüz Vercel\'de. Tahmin edenlerin tarayıcısına kelimenin kendisi hiç gitmiyor, yalnız harf sayısı ve ipucu gidiyor. Bir iki harfle ıskalayan tahmini sunucu sohbete düşürmüyor, yalnız yazana "çok yaklaştın" diyor; yoksa ötekilere hazır ipucu olurdu.',
    tags: ['Next.js 14', 'Socket.io', 'Zustand', 'TypeScript', 'Monorepo'],
    link: 'https://karalama.vercel.app',
    github: 'https://github.com/ahmetakyapi/karalama',
    accent: '#22d3ee',
    gradient: 'linear-gradient(135deg, #22d3ee 0%, #0ea5e9 100%)',
    badge: 'Canlı',
    featured: false,
    postSlug: 'socket-io-ile-oda-tabanli-multiplayer',
  },
  {
    id: 8,
    category: 'Çok Oyunculu Oyun',
    title: 'Dungeon Mates',
    slug: 'dungeon-mates',
    group: 'oyun',
    onlyDark: true,
    description:
      'Tarayıcıda tek başına ya da oda koduyla en fazla dört kişi birlikte oynanan, piksel grafikli bir zindan oyunu. Savaşçı, Büyücü, Okçu ve Şifacı arasından sınıfını seçip on katlık bir zindana iniyorsun; 3, 5, 7 ve 8. katlarda birer boss, onuncu katta Demon bekliyor. Her kat yeniden üretiliyor, kata göre değişen kurallar, güçlendirilmiş canavarlar, yetenek seçimi ve dükkân da bir turu öncekinden ayırıyor.',
    detail:
      'Oyunun bütün mantığı Node sunucusunda saniyede 20 kez işleniyor; tarayıcı yalnız tuş ve eylem gönderiyor, gelen durumu Canvas\'a çiziyor. Haritalar BSP ile sunucuda üretiliyor ve odadaki herkese aynısı gidiyor. Ses efektlerinin hiçbiri dosya değil, Web Audio ile o an üretiliyor.',
    tags: ['Next.js 14', 'Canvas', 'Socket.io', 'WebAudio', 'TypeScript'],
    link: 'https://dungeon-mates.vercel.app',
    github: 'https://github.com/ahmetakyapi/dungeon-mates',
    accent: '#a855f7',
    gradient: 'linear-gradient(135deg, #a855f7 0%, #6366f1 100%)',
    badge: 'Canlı',
    featured: false,
    postSlug: 'bsp-ile-prosedurel-zindan-uretmek',
  },
  {
    id: 9,
    category: 'Klinik Panel',
    title: 'Derinay',
    slug: 'derinay',
    group: 'platform',
    description:
      'Tek kişilik bir klinik pratiğin yönetim paneli: gelir-gider, danışan, seans, fatura, ödeme ve vergi takibi tek sakin arayüzde toplanıyor.',
    detail:
      'Grafikler ana pakete girmiyor; Recharts ayrı bir lazy katmandan yükleniyor. Varsayılan tema açık.',
    tags: ['Next.js 14', 'Drizzle', 'Neon', 'Recharts', 'next-auth v5'],
    link: 'https://derinay.vercel.app',
    github: 'https://github.com/ahmetakyapi/derinay',
    accent: '#0ea5e9',
    tint: '#2f7a6d',
    gradient: 'linear-gradient(135deg, #0ea5e9 0%, #0369a1 100%)',
    badge: 'Canlı',
    featured: true,
  },
  {
    id: 10,
    category: 'Finans',
    title: 'Keşke Alsaydım',
    slug: 'keskealsaydim',
    group: 'arac',
    description:
      'İki hisseyi aynı tarih aralığında ve aynı tutarla karşılaştırıp "onu değil de bunu alsaydım ne olurdu?" sorusunu sayıyla cevaplayan bir yatırım aracı. Sonuçta gün gün değer eğrisi, iki hissenin oynaklığı, aralarındaki korelasyon ve en sert düşüş var. Yanında komisyonlu alış-satış kaydeden bir portföy, izleme listesi ve fiyat alarmları duruyor; kaydettiğin bir karşılaştırmayı giriş gerektirmeyen bir bağlantıyla paylaşabiliyorsun.',
    detail:
      'Bütün toplamlar Türk lirası. ABD hissesi gibi dövizle işlem gören bir varlık bugünkü kurla değil, her işlem gününün kuruyla çevriliyor; sonuca hem hisse hem kur hareketi yansıyor. Arka uç Vercel\'de çalışan Go fonksiyonları, fiyat ve kur verisi Yahoo Finance\'tan geliyor ve Upstash Redis\'te önbelleğe alınıyor.',
    tags: ['React 18', 'TypeScript', 'Go', 'Neon', 'Redis', 'TanStack Query'],
    link: 'https://keskealsaydim.vercel.app',
    github: 'https://github.com/ahmetakyapi/keskealsaydim',
    accent: '#14b8a6',
    gradient: 'linear-gradient(135deg, #14b8a6 0%, #0d9488 100%)',
    badge: 'Canlı',
    featured: false,
  },
  {
    id: 11,
    category: 'Geliştirici Aracı',
    title: 'dev-starter',
    slug: 'dev-starter',
    group: 'arac',
    description:
      'Kendi geliştirme ekosistemim: tasarım tokenları, paylaşılan UI bileşenleri, Next.js şablonları ve projeler arası ortak kural seti. İki npm paketi olarak yayımlanıyor.',
    detail: '@ahmetakyapi/theme ve @ahmetakyapi/ui: token katmanı ve bileşen katmanı ayrı paketlerde.',
    tags: ['TypeScript', 'npm', 'Monorepo', 'Tailwind'],
    link: 'https://github.com/ahmetakyapi/dev-starter',
    github: 'https://github.com/ahmetakyapi/dev-starter',
    accent: '#6366f1',
    gradient: 'linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%)',
    badge: 'GitHub',
    featured: false,
  },
  {
    id: 12,
    category: 'Yardımcı Araç',
    title: 'Ramazan Vakitleri',
    slug: 'ramazan-vakitleri',
    group: 'arac',
    description:
      "Sahur ve iftar vakitlerini, vakte kalan süreyi saniye saniye sayarak gösteren bir Ramazan uygulaması. Türkiye'nin 81 ili ve ilçeleri için Diyanet vakitlerini getiriyor; istersen imsak ile iftarın yanında günün altı vaktini de görüyorsun. Ramazan'ın kaçıncı günü olduğunu yazıyor, Kadir Gecesi'ni ayrıca işaretliyor, bildirime izin verirsen imsaktan ve iftardan 15 dakika önce hatırlatıyor.",
    detail:
      "Vakitler Diyanet verisini yayımlayan ezanvakti.emushaf.net'ten geliyor ve tarayıcıda saklanıyor; bağlantı koparsa son alınan liste gösteriliyor. Ramazan'ın kaçıncı günü olduğu sabit bir tarih tablosundan değil, tarayıcının Hicri takviminden hesaplanıyor. API'nin ilçe listesinde eksik kalan Kadıköy, Üsküdar gibi İstanbul ilçeleri il merkezinin vaktine bağlanıp listeye ekleniyor.",
    tags: ['React 18', 'Vite', 'JavaScript', 'Service Worker'],
    link: 'https://ramazan-vakitleri.vercel.app',
    github: 'https://github.com/ahmetakyapi/ramazan-vakitleri',
    accent: '#f59e0b',
    gradient: 'linear-gradient(135deg, #f59e0b 0%, #d97706 100%)',
    badge: 'Canlı',
    featured: false,
  },
  {
    id: 13,
    category: 'Portfolyo',
    title: 'ahmetakyapi.com',
    slug: 'ahmetakyapi-com',
    group: 'platform',
    description:
      'Bu site. Portfolyo ve teknik blog tek çatı altında. Bütün sayfalar derleme anında üretiliyor; proje ve yazı geçişleri tarayıcının View Transitions API\'siyle, görünüme girme ve kaydırma animasyonları CSS ile.',
    tags: ['Next.js', 'TypeScript', 'Tailwind CSS v4', 'View Transitions', 'Satori OG'],
    link: 'https://ahmetakyapi.com',
    github: 'https://github.com/ahmetakyapi/ahmetakyapi.com',
    accent: '#8b5cf6',
    gradient: 'linear-gradient(135deg, #6366f1 0%, #8b5cf6 50%, #a855f7 100%)',
    badge: 'Canlı',
    featured: false,
    postSlug: 'olculen-hiz-hissedilen-hiz',
  },
]

/** Proje detayı ve OG görseli için; bilinmeyen slug `undefined`. */
export function getProjectBySlug(slug: string): Project | undefined {
  return projects.find((project) => project.slug === slug)
}
